### ISSUE TITLE
アニメ影→陰影画像[画像をここにドラッグ＆ドロップ]に画像を持っていっても反応しない。

### ISSUE THREAD

**Issue by ptyogi** [tori29umai0123/AI-Assistant#1]
他はうまくいくのですが、アニメ影の陰影画像のところだけドラッグ&ドロップしても反応しません。
何が原因かわかりますか？
下の画像は入力線画、canny画像、陰影画像の3箇所に画像を持っていった場合です。

![2024-05-01_111436](https://github.com/tori29umai0123/AI-Assistant/assets/104999084/dfb02871-a4dd-4643-840a-cfa69b734eeb)

**Comment by tori29umai0123** [comment]
https://github.com/tori29umai0123/AI-Assistant/pull/2
修正いたしました。報告ありがとうございます！
